#!/bin/bash

timestamp=$(date +%Y%m%d)

filelist=""
filelist+=" app/*"
filelist+=" config/config-sample.php"
filelist+=" config/template.xml"
filelist+=" config/wwpass_sp_ca.crt"
filelist+=" public/css/jquery.contextMenu.min.css"
filelist+=" public/css/bootstrap.min.css"
filelist+=" public/css/style-int.css"

filelist+=" doc/images/AddButton.png"
filelist+=" doc/images/AddButtonMobile.png"
filelist+=" doc/images/BusinessShare.png"
filelist+=" doc/images/EntryMenu.png"
filelist+=" doc/images/EntryMenuMobile.png"
filelist+=" doc/images/ExportBusiness.png"
filelist+=" doc/images/ExportDialog.png"
filelist+=" doc/images/FolderMenuBusiness.png"
filelist+=" doc/images/FolderMenuMobile.png"
filelist+=" doc/images/IAM.png"
filelist+=" doc/images/ImportBusiness.png"
filelist+=" doc/images/ImportDialog.png"
filelist+=" doc/images/MobileOpenSafe.png"
filelist+=" doc/images/NewEntryDialog.png"
filelist+=" doc/images/NewFileDialog.png"
filelist+=" doc/images/NewNoteDialog.png"
filelist+=" doc/images/NewSafe.png"
filelist+=" doc/images/NewSafeButtonBusiness.png"
filelist+=" doc/images/WhiteList.png"

filelist+=" public/img/SVG2/sprite.svg"
filelist+=" public/img/landing/pic_hand.svg"
filelist+=" public/img/landing/sprite.svg"
filelist+=" public/img/collapse_down.svg"
filelist+=" public/img/collapse_up.svg"
filelist+=" public/img/favicon.ico"
filelist+=" public/img/new_ph_logo.svg"
filelist+=" public/img/outline-https-24px.svg"
filelist+=" public/img/account.svg"
filelist+=" public/img/close-24px.svg"
filelist+=" public/img/save-24px.svg"

filelist+=" public/js/dist/index.js"
filelist+=" public/js/dist/index.js.map"
filelist+=" public/js/dist/login.js"
filelist+=" public/js/dist/login.js.map"
filelist+=" public/js/dist/timers.js"
filelist+=" public/js/dist/timers.js.map"
filelist+=" public/js/dist/upsert_user.js"
filelist+=" public/js/dist/upsert_user.js.map"

filelist+=" public/js/jquery.min.js"
filelist+=" public/js/bootstrap.bundle.min.js"
filelist+=" public/js/bootstrap.bundle.min.js.map"
filelist+=" public/js/jquery.csv.min.js"
filelist+=" public/js/password-generator.js"
filelist+=" views/modals/create_vault.html"
filelist+=" views/modals/delete_item.html"
filelist+=" views/modals/delete_safe.html"
filelist+=" views/modals/folder_ops.html"
filelist+=" views/modals/gen_password.html"
filelist+=" views/modals/idle_and_removal.html"
filelist+=" views/modals/impex.html"
filelist+=" views/modals/rename_file.html"
filelist+=" views/modals/rename_vault.html"
filelist+=" views/modals/safe_users.html"
filelist+=" views/modals/share_by_mail.html"
filelist+=" views/modals/show_creds.html"
filelist+=" views/error_page.html"
filelist+=" views/expired.html"
filelist+=" views/feedback.html"
filelist+=" views/feedback_action.html"
filelist+=" views/index.html"
filelist+=" views/login_reg.html"
filelist+=" views/message_page.html"
filelist+=" views/notsupported.html"
filelist+=" views/registration_action.html"
filelist+=" views/request_mail.html"
filelist+=" views/layout.html"
filelist+=" views/upsert_user.html"
filelist+=" views/sprite.svg"
filelist+=" account.php"
filelist+=" composer.json"
filelist+=" composer.lock"
filelist+=" create_file.php"
filelist+=" create_user.php"
filelist+=" create_vault.php"
filelist+=" delete.php"
filelist+=" delete_safe.php"
filelist+=" error_page.php"
filelist+=" expired.php"
filelist+=" favicon.ico"
filelist+=" feedback.php"
filelist+=" feedback_action.php"
filelist+=" file_ops.php"
filelist+=" folder_ops.php"
filelist+=" form_filled.php"
filelist+=" get_user_data.php"
filelist+=" getticket.php"
filelist+=" help.php"
filelist+=" impex.php"
filelist+=" index.php"
filelist+=" items.php"
filelist+=" login.php"
filelist+=" logout.php"
filelist+=" maintenance_off.html"
filelist+=" move.php"
filelist+=" notsupported.php"
filelist+=" registration_action.php"
filelist+=" safe_acl.php"
filelist+=" update_ticket.php"
filelist+=" update_vault.php"
filelist+=" robots.txt"

filelist+=" public/img/formentera-beach.jpeg"
filelist+=" public/js/dist/iam.js"
filelist+=" public/js/dist/iam.js.map"
filelist+=" views/help.html"
filelist+=" views/iam.html"
filelist+=" views/ldap.html"
filelist+=" views/login.html"
filelist+=" delete_user.php"
filelist+=" edit_user.php"
filelist+=" iam.php"
filelist+=" ldap.php"
filelist+=" InstallingPassHubOnUbuntu18.04.md" 
filelist+=" public/js/landing.js"
filelist+=" public/css/style.css"
filelist+=" public/img/landing/app_apple.svg"
filelist+=" public/img/landing/app_google.svg"
filelist+=" public/img/landing/bg_big.svg"
filelist+=" public/img/landing/bg_small.svg"
filelist+=" public/img/landing/logo.svg"










# filelist+=" public/css/font/context-menu-icons.eot"
# filelist+=" public/css/font/context-menu-icons.ttf"
# filelist+=" public/css/font/context-menu-icons.woff"
# filelist+=" public/css/font/context-menu-icons.woff2"
# filelist+=" js/dist/item_form.js"
# filelist+=" js/dist/new_file.js"
# filelist+=" views/modals/account.html"
# filelist+=" views/form_filled.html"
# filelist+=" views/item_form.html"
# filelist+=" views/new_file.html"
# filelist+=" views/progress.html"
# filelist+=" create.php"
# filelist+=" edit.php"
# filelist+=" new.php"
# filelist+=" newfile.php"
# filelist+=" update.php"
# filelist+=" src/db/SessionHandler.php"
# filelist+=" src/db/file.php"
# filelist+=" src/db/iam_ops.php"
# filelist+=" src/db/item.php"
# filelist+=" src/db/safe.php"
# filelist+=" src/db/user.php"
# filelist+=" src/functions.php"
# filelist+=" src/template.php"
# filelist+=" src/google_drive_files.php"
# filelist+=" src/s3_files.php"





echo "Arch"

rm -f /tmp/passhub.business.$timestamp.tgz
cp public/css/style-int.biz.css public/css/style-int.css
cp public/img/favicon.net.ico public/img/favicon.ico
tar czf /tmp/passhub.business.$timestamp.tgz --transform 's,^,passhub/,' $filelist
mv /tmp/passhub.business.$timestamp.tgz .

echo $filelist

echo "Done"
