#!/bin/bash

filelist=" img doc css/font"

# business specific files
filelist+=" account.php"
filelist+=" delete_user.php"
filelist+=" edit_user.php"
filelist+=" iam.php"
#filelist+=" reg_code_check.php"
filelist+=" src/templates/account.html"
filelist+=" src/templates/iam.html"
filelist+=" src/templates/login_reg.html"
filelist+=" InstallingPassHubOnUbuntu16.04.md"
filelist+=" InstallingPassHubOnUbuntu18.04.md"
#filelist+=" src/templates/reg_code_check.html"
filelist+=" src/templates/registration_action.html"
#filelist+=" src/templates/modals/invite_by_mail.html"
filelist+=" src/templates/modals/share_by_mail.html"
filelist+=" registration_action.php"
filelist+=" src/templates/request_mail.html"
filelist+=" robots.txt"

# public service specific
#filelist+=" accept_terms.php"
#filelist+=" src/templates/policy.html"
#filelist+=" src/templates/terms_dialog.html"
#filelist+=" src/templates/user_agreement.html"
#filelist+=" privacy.php"
#filelist+=" cookie_policy.php"
#filelist+=" terms.php"

filelist+=" js/dist/iam.js"
filelist+=" js/dist/index.js"
filelist+=" js/dist/item_form.js"
filelist+=" js/dist/login.js"
filelist+=" js/dist/new_file.js"
filelist+=" js/dist/timers.js"
filelist+=" js/dist/upsert_user.js"

filelist+=" add_by_invite.php"
#filelist+=" business.php"
filelist+=" config/config-sample.php"
filelist+=" config/template.xml"
filelist+=" config/wwpass_sp_ca.crt"
filelist+=" create.php"
filelist+=" create_file.php"
filelist+=" create_user.php"
filelist+=" create_vault.php"
filelist+=" css/jquery.contextMenu.min.css"
filelist+=" css/style-header.css"
filelist+=" css/style.css"
#filelist+=" css/style.test.css"
filelist+=" delete.php"
filelist+=" delete_safe.php"
filelist+=" edit.php"
filelist+=" error_page.php"
filelist+=" expired.php"
filelist+=" favicon.ico"
filelist+=" feedback.php"
filelist+=" feedback_action.php"
filelist+=" file_ops.php"
filelist+=" folder_ops.php"
filelist+=" get_sharing_code.php"
filelist+=" get_sharing_status.php"
filelist+=" get_user_data.php"
filelist+=" getticket.php"
filelist+=" help.php"
filelist+=" impex.php"
filelist+=" index.php"
#filelist+=" js/FileSaver.min.js"
#filelist+=" js/forge.min.js"
#filelist+=" js/functions.js"
#filelist+=" js/impex.js"
#filelist+=" js/jquery.contextMenu.min.js"
filelist+=" js/jquery.ui.position.min.js"
filelist+=" js/jquery.csv.js"
filelist+=" js/landing.js"
#filelist+=" js/passhub.js"
filelist+=" js/password-generator.js"
filelist+=" js/svg-injector.js"
#filelist+=" js/wwpass.universal.js"
filelist+=" login.php"
filelist+=" logout.php"
filelist+=" maintenance_off.html"
#filelist+=" monster.json.php"
filelist+=" move.php"
filelist+=" new.php"
filelist+=" newfile.php"
filelist+=" notsupported.php"
filelist+=" safe_acl.php"
#filelist+=" security.php"
filelist+=" src/cookie.php"
filelist+=" src/db/SessionHandler.php"
filelist+=" src/db/file.php"
filelist+=" src/db/iam_ops.php"
filelist+=" src/db/item.php"
filelist+=" src/db/safe.php"
filelist+=" src/db/user.php"
filelist+=" src/functions.php"
filelist+=" src/google_drive_files.php"
#filelist+=" src/lib/wwpass.php"
filelist+=" src/template.php"
#filelist+=" src/templates/business.html"
filelist+=" src/templates/error_page.html"
filelist+=" src/templates/expired.html"
filelist+=" src/templates/feedback.html"
filelist+=" src/templates/feedback_action.html"
#filelist+=" src/templates/help-pub.html"
filelist+=" src/templates/help.html"
filelist+=" src/templates/item_form.html"
#filelist+=" src/templates/item_list.html"
#filelist+=" src/templates/item_pane.html"
filelist+=" src/templates/index.html"
filelist+=" src/templates/login.html"
filelist+=" src/templates/login_on_mobile.html"
#filelist+=" src/templates/login_test.html"
filelist+=" src/templates/modals/accept_sharing.html"
filelist+=" src/templates/modals/create_vault.html"
filelist+=" src/templates/modals/delete_item.html"
filelist+=" src/templates/modals/delete_safe.html"
filelist+=" src/templates/modals/folder_ops.html"
filelist+=" src/templates/modals/gen_password.html"
filelist+=" src/templates/modals/idle_and_removal.html"
filelist+=" src/templates/modals/impex.html"
filelist+=" src/templates/modals/rename_file.html"
filelist+=" src/templates/modals/rename_vault.html"
filelist+=" src/templates/modals/safe_users.html"
filelist+=" src/templates/modals/share_safe.html"
filelist+=" src/templates/modals/show_creds.html"
filelist+=" src/templates/new_file.html"
filelist+=" src/templates/notsupported.html"
filelist+=" src/templates/progress.html"
#filelist+=" src/templates/security.html"
filelist+=" src/templates/top.html"
filelist+=" src/templates/upsert_user.html"
#filelist+=" src/templates/vault_list.html"
filelist+=" update.php"
filelist+=" update_ticket.php"
filelist+=" update_vault.php"
filelist+=" upgrade_user.php"
filelist+=" composer.json"
filelist+=" composer.lock"
#filelist+=" package.json"
#filelist+=" package-lock.json"

code=$(date +%Y%m%d)
echo "Arch"

rm -f /tmp/passhub.business.$code.tgz
tar czf /tmp/passhub.business.$code.tgz --transform 's,^,passhub/,' $filelist
mv /tmp/passhub.business.$code.tgz .

echo "Done"
